### PR TITLE
fix typo in informationStep.svelte & correct two URLs

### PR DESCRIPTION
**Pull request by edisim**
retrieve → retrieveAllProducts

### CODE REVIEW

**Review by vickywane — APPROVED** [review]

**Comment by vickywane** [comment]
Thanks, @edisim for the correction. 

I'll merge this ❤️.

**Comment by nrthbound** [comment]
Now when going to the cart, you get `Uncaught (in promise) ReferenceError: retrieveAllProducts is not defined` after this change. There are quite a few other broken parts. Documentation says to `mv creds.template.js creds.js` but you didn't update the imports, so making that change breaks the build. Will fork and submit PRs shortly.

**Comment by vickywane** [comment]
@nrthbound Apologies for the breaking changes. 

I didn't have enough time to pull and test the changes locally before merging them. 

I'd be glad to review and test your pull request. I also plan to write tests to prevent such regressions later on. 

❤️

**Comment by nrthbound** [comment]
> @nrthbound Apologies for the breaking changes.
> 
> I didn't have enough time to pull and test the changes locally before merging them.
> 
> I'd be glad to review and test your pull request. I also plan to write tests to prevent such regressions later on.
> 
> ❤️

Sounds good. I've put in 2 PR's, and I have a big one coming that fixes the use of CSS instead of Tailwind, and the removal of the Tailwind CDN and implements in properly with V3's built-in purge. I would have entered them but issues are disabled for this repo, so I had to post them here. ^_^

**Pull request merged**
